server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:postgresql://localhost:3432/conferenc?currentSchema=conferenc
    username: conferenc
    password: conferenc
    driver-class-name: org.postgresql.Driver
  flyway:
    url: jdbc:postgresql://localhost:3432/conferenc?currentSchema=conferenc
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    encoding: UTF-8
    create-schemas: true
    schemas: conferenc

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

springdoc:
  webjars:
    prefix:
  swagger-ui:
    path: /store/v3/swagger-ui.html
  api-docs:
    enabled: true
    path: /store/v3/api-docs